### ISSUE TITLE
FR: specify action taken on app buttons

### ISSUE THREAD

**Issue by Madseason41** [iantrich/roku-card#24]
I like the rewrite of this app as it affords the ability to use as a universal remote!

What are the requirements for the app icon? PNG, webp, pixel size?

I was able to get an icon to render on Firefox, but not Chrome, and the iOS Beta App. Also I couldn't get the icon to render when putting the .webp file in a sub-directory. 

Ex. It worked by using /local/sample.webp

It did not work when using /local/icons/sample.webp

Feature request would be to:

Allow using the app locations/ icons to call any function, much like the other buttons.

Allow using sub-directory for icon placement (if this is possible/ not an setup error).

Great work!

**Comment by iantrich** [comment]
you just provide the URL for the `img` src. I don't restrict it in anyway.

I'm not going to add custom service calls to the apps, but anyone is welcome to submit a PR to.

**Comment by HABuild** [comment]
I installed this via HACs on hass.io, I don't think the apps buttons have any function as they are. Are they supposed to? I wasn't really sure as I ended up using this card for a universal mqtt remote using service call switches. 

Also
I did finally find the icon location to add a webp icon. 
/local/ = /www/ on hass.io 
but thats not super clear in your example on the readme, if you could update the directory and point out that the files need to be sourced and copied to that directory. Most hassio installs start from /config/ so the actual dir list would be /config/www/

Thanks heaps for a simple to configure universal remote though!!

**Comment by iantrich** [comment]
impmlemented in 1.0.5
