### ISSUE TITLE
Volume Buttons

### ISSUE THREAD

**Issue by abcde57219** [iantrich/roku-card#35]
I am not able to use the power or volume buttons because of the way my Roku is fed to multiple televisions.  Is there a way that the power button and volume buttons can be removed?  It might also be nice to replace the Volume buttons with Channel buttons.  Thanks.

**Comment by datwood2009** [comment]
I have an issue with the Volume Up button.  All my other buttons work fine, but when I press the Volume Up button it acts like a Pause/Play button.

**Comment by haux03** [comment]
> I have an issue with the Volume Up button. All my other buttons work fine, but when I press the Volume Up button it acts like a Pause/Play button.

I had an issue with volume up as well, changed its config from tap_action to double_tap_action same as the volume down and it worked fine after that.

**Comment by datwood2009** [comment]
@haux03 thank you...that helped!

**Comment by iantrich** [comment]
@abcde57219 set `tv: false`
