### ISSUE TITLE
Doesn't build with latest custom-card-helpers

### ISSUE THREAD

**Issue by supachris28** [iantrich/roku-card#36]
Latest `custom-card-helpers` changes exported types.d.ts and removes `ActionHandlerOptions` which breaks the build of this application.

Reverting to previous build allows `roku-card` to build.

**Comment by iantrich** [comment]
Why are you trying to use answer version?

**Comment by supachris28** [comment]
I'll pulled the repo, ran `npm i` and it installed the latest version as the dependency is specified with a caret and the breaking change wasn't deployed as a major version bump. Then when running rollup it explodes. The dependency should be pinned, or the change to `custom-card-helpers` should be a major version bump to stop this happening.

**Comment by iantrich** [comment]
Ah, gotcha 👍

**Comment by iantrich** [comment]
Looks like I lost some code 😭 when I reimaged my machine that wasn't checked in to git but was published to npm...I'm awful...

**Comment by iantrich** [comment]
should be fixed now

**Comment by supachris28** [comment]
Doh! That's a pain. Good work on sorting :)
