### ISSUE TITLE
icons not loading in 0.110

### ISSUE THREAD

**Issue by iantrich** [iantrich/roku-card#40]
**Checklist:**

- [ ] I updated to the latest version available
- [ ] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**

**Browser and Operating System:**

**Description of problem:**

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by iantrich** [comment]
switch to ha-icon-button

**Comment by JManDoo** [comment]
- [ X] I updated to the latest version available 

- [ X] I tried multiple browsers and mobile phones
Release with the issue: All  after .110 update
Browser and os: Edge, Edge Chromium, Chrome, Safari....Win 10 1909, iOS 13.5

<img width="744" alt="Missing buttons" src="https://user-images.githubusercontent.com/21066923/81886825-4dee8680-9563-11ea-974b-216b13a9f8d4.PNG">

**Comment by iantrich** [comment]
Fixed in 1.1.1

**Comment by JManDoo** [comment]
![72095366-27B2-4917-8239-163CF9601181](https://user-images.githubusercontent.com/21066923/81893321-0f60c800-9573-11ea-89db-01279682a8cd.png)

**Comment by JManDoo** [comment]
![77DA4205-3D82-49F7-95F8-EE3C61FAF932](https://user-images.githubusercontent.com/21066923/81893535-7da58a80-9573-11ea-9bcf-5a2c8a32c856.jpeg)

**Comment by iantrich** [comment]
build failed. 1.1.2 should work

**Comment by JManDoo** [comment]
Same on 1.1.2 mdi icons missing

**Comment by iantrich** [comment]
Yeah but I broke it for everyone not on beta 😅
