### ISSUE TITLE
Missing navigation buttons

### ISSUE THREAD

**Issue by MightyMilster** [iantrich/roku-card#42]
Hi. With the latest update (1.1.2), I seem to have lost my navigation buttons. Select, up, down, left and right for example. When you hover over the button locations, the links appear to be there - but the visual elements are missing. I'm running v0.109.6. I tried returning to a default HA theme in case that was it; but no dice. Thanks, m

**Comment by thep0tter** [comment]
Same here.  Attempting to roll back to 1.1.1 throws an error "No Content to Download"
![roku-card](https://user-images.githubusercontent.com/64334340/82022221-24a42800-9641-11ea-9e70-a9872867a3c3.png)

**Comment by iantrich** [comment]
use 1.1.0 for now

**Comment by iantrich** [comment]
version 1.1.1 and above will be for HA 0.110.0 and greater. have restricted it in the hacs file and added a note in the readme

**Comment by omriasta** [comment]
Looks like 1.1.0  as well as all the older versions are also restricted to version 0.110.

**Comment by pwillia7** [comment]
Everything is restricted to something other than the beta branch accessible through supervisor. I was trying to get this setup today but it looks not possible through HACS.

**Comment by iantrich** [comment]
I'll see if I can't clean it up tomorrow
