### ISSUE TITLE
After updating to .111 the card no longer seems to work

### ISSUE THREAD

**Issue by nicxvan** [iantrich/roku-card#43]
- [1.1.3 ] I updated to the latest version available
- [ * ] I cleared the cache of my browser

**Release with the issue:**
1.1.3
Docker on a nuc

I'm on firefox Macos

**Description of problem:**
When I click any buttons on the card I get the following message:
`Failed to call service remote/send_command. Service not found.`

**Javascript errors shown in the web inspector (if applicable):**

```
Loading module from “https://ha.reverseproxy/community_plugin/roku-card/roku-card.js” was blocked because of a disallowed MIME type (“text/plain”).

uncaught exception: https://ha.reverseproxy.com/community_plugin/roku-card/roku-card.js

uncaught exception: Object
```

Card yaml
```
apps:
  - app: Netflix
    image: /local/netflix-icon.png
  - app: Plex - Stream Free Movies & TV
    image: /local/Plex-icon.png
  - app: Prime Video
    image: /local/Amazon-icon.png
  - app: Roku Media Player
    image: /local/Media-windows-media-player-icon.png
entity: media_player.bedroom_roku
name: Bedroom roku
remote: remote.bedroom
style: |
  ha-card {
    --ha-card-background: black;
  }
  .card-header {
    color: white;
  }
  paper-icon-button {
    color: grey;
  }
  .card-content {
    padding: 0
  }
theme: darkpurple
tv: false
type: 'custom:roku-card'

```

**Comment by iantrich** [comment]
Does your remote entity exist still?

**Comment by nicxvan** [comment]
I see the remote is there, but the status is red, let me try adding the rokus through the ui.

**Comment by nicxvan** [comment]
That was it:
Removing platform: roku from yaml and using the ui to add them fixed it!
