### ISSUE TITLE
Add icon option to apps

### ISSUE THREAD

**Issue by blitzaxt** [iantrich/roku-card#46]
Currently as far as I can tell the only way to add an image to the apps is to put an image in the proper location and pointing to it. 

It would be really helpful to be able to use the MDI icons as well for example: https://iconify.design/icon-sets/mdi/netflix.html mdi-netflix
Thanks!

**Comment by iantrich** [comment]
Implemented in https://github.com/iantrich/roku-card/releases/tag/1.1.4

**Comment by blitzaxt** [comment]
You rock! Thank you so much!
