### ISSUE TITLE
tap action on app buttons with icons doesent work

### ISSUE THREAD

**Issue by Maxakipust** [iantrich/roku-card#52]
**Checklist:**

- [ ] I updated to the latest version available
- [ ] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**

**Browser and Operating System:**

**Description of problem:**

When configuring an app button with an icon and other config items, the config items dont work. This is because on line 164 you are missing `.config=${this._config.apps[index]}`
**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by iantrich** [comment]
Thanks
