### ISSUE TITLE
Volume up not working

### ISSUE THREAD

**Issue by wlraider70** [iantrich/roku-card#54]
The volume up button is not working on this card. 

The 'default' media player vol+ is working. 
entity: media_player.bedroom_tv
type: media-control

Bonus Q, since I don't want to get crazy:
Do I ned to download the app images? for example  image: /local/netflix-icon.png is blank to me.

**Comment by iantrich** [comment]
App images are not included in the distribution

**Comment by iantrich** [comment]
Share your card config

**Comment by wlraider70** [comment]
I got it figured out, sorry. I was confused when some buttons were working. I had the volume specific settings messed up. I removed them and the card worked perfect. 

While I got you though, I'm struggling with the images. I can't tell if its the file location, the dockerization or the formatting/size of the file itself. Regardless it's not displaying. 
Any pointers? I put the files in the community/roku-card/ folder.

thanks

**Comment by iantrich** [comment]
Just out them in your `www` folder
