### ISSUE TITLE
Integrate into Roku Integration?

### ISSUE THREAD

**Issue by jacobkaad01** [iantrich/roku-card#55]
Hello I know this is a little late in Hacktoberfest but it just occurred to me to ask why not shift this as a native card within the Roku Integration similar to how the new Xbox integration has a controller like picture card. Maybe there's alot of hurtles to that but I feel like the more stuff that is natively supported the more friendly and used it will get as some users that may come to Home Assistant may never touch addons besides the native integrations (particularly the ones that are auto-discovered). Then this way the remote can use/have the ability to select if user chooses the custom app buttons (or one of them) as the Roku Media Browser function.

**Comment by iantrich** [comment]
A bit too specialized for core IMO. Also, Xbox does not have a native card, it is just a picture-elements card in that video shown.
