### ISSUE TITLE
Option to turn off annoying haptic vibration

### ISSUE THREAD

**Issue by setdetnet** [iantrich/roku-card#57]
I'm always frustrated when I disable snoring haptic kind of feedback for example, vibration

Config option please in the card config, to turn it off.
.

**Comment by iantrich** [comment]
I don't use this card anymore, but that was always something I meant to update. I've added a `haptic` option the latest release: https://github.com/iantrich/roku-card/releases/tag/1.2.0

**Comment by setdetnet** [comment]
Appreciate your help. Thank you.
