### ISSUE TITLE
infinite load

### ISSUE THREAD

**Issue by MacelinCane** [iantrich/roku-card#65]
**Checklist:**

- [ x ] I updated to the latest version available
- [ x ] I cleared the cache of my browser

**Release with the issue:**
Home Assistant 2021.9.1
Frontend version: 20210830.0 - latest

**Last working release (if known):**

**Browser and Operating System:**
W10 Pro
Chrome Version 92.0.4515.159 (Official Build) (64-bit)

**Description of problem:**
in HACS, after searching for the repo, roku-card, and finding it, clicking on it starts an infinite load.  I've restarted HA and HACS to clear this but nothing has worked. 

In HA logs the error is generated each time I attempt it. This is repeatable, reliably.
```
Logger: custom_components.hacs
Source: custom_components/hacs/api/hacs_repository.py:108
Integration: HACS (documentation, issues)
First occurred: 5:41:15 PM (1 occurrences)
Last logged: 5:41:15 PM

Could not use repository with ID 164367214 ('NoneType' object has no attribute 'get_releases')
```

**Javascript errors shown in the web inspector (if applicable):**

```
none
```

**Additional information:**
![image](https://user-images.githubusercontent.com/57817530/132068675-708e34ef-afb7-41ee-8fd6-c583cf4d73ad.png)

Thank you - I'm psyched to try this out!

**Comment by iantrich** [comment]
You should open an issue with HACS
