### ISSUE TITLE
Suggestion power button as indicator

### ISSUE THREAD

**Issue by omriasta** [iantrich/roku-card#7]
Change the power button color based on TV status. I'm no good with js but you can easily get the TV power state from here:
curl -s GET "http://rokuip:8060/query/device-info" | grep power
I'm not sure if Hass component has an attribute for it or not...

**Comment by iantrich** [comment]
The HA plugin does not report power state. I used to use the local API for everything in this card, so should be easy to add. I'll check it out

**Comment by iantrich** [comment]
hmm, I'd have to add the IP address back...don't really want to do that. I think updating the Roku component is the better route to properly report as "off" instead of "home" for TVs

**Comment by iantrich** [comment]
Looks like we'll need it to the python lib first:
https://github.com/jcarbaugh/python-roku/blob/master/roku/core.py#L227

**Comment by iantrich** [comment]
I knew this idea sounded familiar :)

https://github.com/jcarbaugh/python-roku/pull/37

Looks like the repo is abandoned...perfect

**Comment by iantrich** [comment]
So, I'll give the maintainer a week or two to respond to my last message. Otherwise I think we'll fork it, add the power support and apply a patch to HA core.

**Comment by iantrich** [comment]
So I've been added as a maintainer to the module, I'll try to find some time this weekend to figure out the ins and outs of the module and how best to proceed.

**Comment by iantrich** [comment]
Finally got pypi access this morning; a new release will be out tonight and will include tv controls. Will then look into how to update the Roku component to get this info for us

**Comment by edgitmecode** [comment]
Installation step 3 example missing " " at -type: "custom:roku-card"
Step 3 example also shows power: service. I could not get power button to work until removing this option.
