### ISSUE TITLE
Icons missing with latest HA update

### ISSUE THREAD

**Issue by donnievawter** [iantrich/roku-card#70]
**Checklist:**

- [x ] I updated to the latest version available
- [ x] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**

**Browser and Operating System:**

With latest update to Home Assistant (11.0) the icons on buttons do not show up
![image](https://user-images.githubusercontent.com/89166921/140370251-254f1bce-c0ac-4711-b50a-c1a0d701849f.png)
I have tried in both Safari and Edge with same result.
The new version on HA now has an icon picker. I wonder if that breaks the reference in your javascript to mdi:xxx. Maybe they have moved them?

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by donnievawter** [comment]
Latest update fixes, thanks

**Comment by bweise84** [comment]
This is not fixed for me in 1.2.3. Cleared cache, uninstalled and reinstalled. Still no icons besides the app icons
